# Import required libiraries

In [ ]:
!pip install rdkit
import pandas as pd
import numpy as np
from rdkit import Chem
from rdkit.Chem import Descriptors

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: rdkit in /usr/local/lib/python3.7/dist-packages (2022.9.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (from rdkit) (1.21.6)
Requirement already satisfied: Pillow in /usr/local/lib/python3.7/dist-packages (from rdkit) (7.1.2)

# Import and process datasets

## AqSolDB dataset

In [ ]:
# Importing AqSolDB. Source https://www.nature.com/articles/s41597-019-0151-1 
AqSolDB = pd.read_csv('/content/drive/MyDrive/WithNicolas/SoulPred/harvard_data.csv')

In [ ]:
AqSolDB

,ID,Name,InChI,InChIKey,SMILES,Solubility,SD,Ocurrences,Group,MolWt,...,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,A-3,"N,N,N-trimethyloctadecan-1-aminium bromide",InChI=1S/C21H46N.BrH/c1-5-6-7-8-9-10-11-12-13-...,SZEMGTQCPRNXEG-UHFFFAOYSA-M,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,0.000000,1,G1,392.510,...,17.0,142.0,0.0,0.0,0.0,0.0,0.00,158.520601,0.000000e+00,210.377334
1,A-4,Benzo[cd]indol-2(1H)-one,InChI=1S/C11H7NO/c13-11-8-5-1-3-7-4-2-6-9(12-1...,GPYLCFQEKPUWLD-UHFFFAOYSA-N,O=C1Nc2cccc3cccc1c23,-3.254767,0.000000,1,G1,169.183,...,0.0,62.0,2.0,0.0,1.0,3.0,29.10,75.183563,2.582996e+00,511.229248
2,A-5,4-chlorobenzaldehyde,InChI=1S/C7H5ClO/c8-7-3-1-6(5-9)2-4-7/h1-5H,AVPYQKSLYISFPO-UHFFFAOYSA-N,Clc1ccc(C=O)cc1,-2.177078,0.000000,1,G1,140.569,...,1.0,46.0,1.0,0.0,0.0,1.0,17.07,58.261134,3.009782e+00,202.661065
3,A-8,"zinc bis[2-hydroxy-3,5-bis(1-phenylethyl)benzo...",InChI=1S/2C23H22O3.Zn/c2*1-15(17-9-5-3-6-10-17...,XTUPUYCJWKHGSW-UHFFFAOYSA-L,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,0.000000,1,G1,756.226,...,10.0,264.0,6.0,0.0,0.0,6.0,120.72,323.755434,2.322963e-07,1964.648666
4,A-9,4-({4-[bis(oxiran-2-ylmethyl)amino]phenyl}meth...,InChI=1S/C25H30N2O4/c1-5-20(26(10-22-14-28-22)...,FAUAZXVRLVIARB-UHFFFAOYSA-N,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,0.000000,1,G1,422.525,...,12.0,164.0,2.0,4.0,4.0,6.0,56.60,183.183268,1.084427e+00,769.899934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,I-84,tetracaine,InChI=1S/C15H24N2O2/c1-4-5-10-16-14-8-6-13(7-9...,GKCBAIGFKIBETG-UHFFFAOYSA-N,C(c1ccc(cc1)NCCCC)(=O)OCCN(C)C,-3.010000,0.000000,1,G1,264.369,...,8.0,106.0,1.0,0.0,0.0,1.0,41.57,115.300645,2.394548e+00,374.236893
9978,I-85,tetracycline,InChI=1S/C22H24N2O8/c1-21(31)8-5-4-6-11(25)12(...,OFVLGDICTFRJMM-WESIUVDSSA-N,OC1=C(C(C2=C(O)[C@@](C(C(C(N)=O)=C(O)[C@H]3N(C...,-2.930000,0.000000,1,G1,444.440,...,2.0,170.0,1.0,0.0,3.0,4.0,181.62,182.429237,2.047922e+00,1148.584975
9979,I-86,thymol,InChI=1S/C10H14O/c1-7(2)9-5-4-8(3)6-10(9)11/h4...,MGSRCZKZVOBKFT-UHFFFAOYSA-N,c1(cc(ccc1C(C)C)C)O,-2.190000,0.019222,3,G5,150.221,...,1.0,60.0,1.0,0.0,0.0,1.0,20.23,67.685405,3.092720e+00,251.049732
9980,I-93,verapamil,"InChI=1S/C27H38N2O4/c1-20(2)27(19-28,22-10-12-...",SGTNSNPWRIOYBX-UHFFFAOYSA-N,COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2...,-3.980000,0.000000,1,G1,454.611,...,13.0,180.0,2.0,0.0,0.0,2.0,63.95,198.569223,2.023333e+00,938.203977
9981,I-94,warfarin,InChI=1S/C19H16O4/c1-12(20)11-15(13-7-3-2-4-8-...,PJVWKTKQMONHTI-UHFFFAOYSA-N,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,-4.780000,0.450506,3,G5,308.333,...,4.0,116.0,3.0,0.0,0.0,3.0,67.51,132.552025,2.258072e+00,909.550973

In [ ]:
# chech for any null values in the dataset
AqSolDB.isnull().sum()

ID                     0
Name                   0
InChI                  0
InChIKey               0
SMILES                 0
Solubility             0
SD                     0
Ocurrences             0
Group                  0
MolWt                  0
MolLogP                0
MolMR                  0
HeavyAtomCount         0
NumHAcceptors          0
NumHDonors             0
NumHeteroatoms         0
NumRotatableBonds      0
NumValenceElectrons    0
NumAromaticRings       0
NumSaturatedRings      0
NumAliphaticRings      0
RingCount              0
TPSA                   0
LabuteASA              0
BalabanJ               0
BertzCT                0
dtype: int64

In [ ]:
# Drop unnecessary columns
AqSolDB_cured = (
    AqSolDB.drop(['ID', 'Name', 'InChI', 'InChIKey', 'SD', 'Ocurrences', 'Group'], axis=1)
)

In [ ]:
AqSolDB_cured # now it contains the necessary columns only

,SMILES,Solubility,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,392.510,3.95810,102.4454,23.0,0.0,0.0,2.0,17.0,142.0,0.0,0.0,0.0,0.0,0.00,158.520601,0.000000e+00,210.377334
1,O=C1Nc2cccc3cccc1c23,-3.254767,169.183,2.40550,51.9012,13.0,1.0,1.0,2.0,0.0,62.0,2.0,0.0,1.0,3.0,29.10,75.183563,2.582996e+00,511.229248
2,Clc1ccc(C=O)cc1,-2.177078,140.569,2.15250,36.8395,9.0,1.0,0.0,2.0,1.0,46.0,1.0,0.0,0.0,1.0,17.07,58.261134,3.009782e+00,202.661065
3,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,756.226,8.11610,200.7106,53.0,6.0,2.0,7.0,10.0,264.0,6.0,0.0,0.0,6.0,120.72,323.755434,2.322963e-07,1964.648666
4,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,422.525,2.48540,119.0760,31.0,6.0,0.0,6.0,12.0,164.0,2.0,4.0,4.0,6.0,56.60,183.183268,1.084427e+00,769.899934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9977,C(c1ccc(cc1)NCCCC)(=O)OCCN(C)C,-3.010000,264.369,2.61700,78.6762,19.0,4.0,1.0,4.0,8.0,106.0,1.0,0.0,0.0,1.0,41.57,115.300645,2.394548e+00,374.236893
9978,OC1=C(C(C2=C(O)[C@@](C(C(C(N)=O)=C(O)[C@H]3N(C...,-2.930000,444.440,-0.21440,109.5409,32.0,9.0,6.0,10.0,2.0,170.0,1.0,0.0,3.0,4.0,181.62,182.429237,2.047922e+00,1148.584975
9979,c1(cc(ccc1C(C)C)C)O,-2.190000,150.221,2.82402,46.9328,11.0,1.0,1.0,1.0,1.0,60.0,1.0,0.0,0.0,1.0,20.23,67.685405,3.092720e+00,251.049732
9980,COc1ccc(CCN(C)CCCC(C#N)(C(C)C)c2ccc(OC)c(OC)c2...,-3.980000,454.611,5.09308,131.6560,33.0,6.0,0.0,6.0,13.0,180.0,2.0,0.0,0.0,2.0,63.95,198.569223,2.023333e+00,938.203977
9981,CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O,-4.780000,308.333,3.60960,87.7318,23.0,4.0,1.0,4.0,4.0,116.0,3.0,0.0,0.0,3.0,67.51,132.552025,2.258072e+00,909.550973

In [ ]:
# save cured df

AqSolDB_cured.to_csv('/content/drive/MyDrive/WithNicolas/SoulPred/aqsoldb_cured.csv')

## Delaney-processed dataset

In [ ]:
# import delaney dataset. Source https://github.com/deepchem/deepchem/blob/master/datasets/delaney-processed.csv
delaney = pd.read_csv('/content/drive/MyDrive/WithNicolas/SoulPred/delaney-processed.csv')

In [ ]:
delaney

,Compound ID,ESOL predicted log solubility in mols per litre,Minimum Degree,Molecular Weight,Number of H-Bond Donors,Number of Rings,Number of Rotatable Bonds,Polar Surface Area,measured log solubility in mols per litre,smiles
0,Amigdalin,-0.974,1,457.432,7,3,7,202.32,-0.770,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...
1,Fenfuram,-2.885,1,201.225,1,2,2,42.24,-3.300,Cc1occc1C(=O)Nc2ccccc2
2,citral,-2.579,1,152.237,0,0,4,17.07,-2.060,CC(C)=CCCC(C)=CC(=O)
3,Picene,-6.618,2,278.354,0,5,0,0.00,-7.870,c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43
4,Thiophene,-2.232,2,84.143,0,1,0,0.00,-1.330,c1ccsc1
...,...,...,...,...,...,...,...,...,...,...
1123,halothane,-2.608,1,197.381,0,0,0,0.00,-1.710,FC(F)(F)C(Cl)Br
1124,Oxamyl,-0.908,1,219.266,1,0,1,71.00,0.106,CNC(=O)ON=C(SC)C(=O)N(C)C
1125,Thiometon,-3.323,1,246.359,0,0,7,18.46,-3.091,CCSCCSP(=S)(OC)OC
1126,2-Methylbutane,-2.245,1,72.151,0,0,1,0.00,-3.180,CCC(C)C
1127,Stirofos,-4.320,1,365.964,0,1,5,44.76,-4.522,COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl

In [ ]:
delaney = (
    delaney[['smiles', 'measured log solubility in mols per litre']] # extract only the required columns
    .rename(columns={'measured log solubility in mols per litre':'Solubility', 'smiles':'SMILES'}) # rename them to make all dfs hve the same col names
)

In [ ]:
delaney

                                                 SMILES  Solubility
0     OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...      -0.770
1                                Cc1occc1C(=O)Nc2ccccc2      -3.300
2                                  CC(C)=CCCC(C)=CC(=O)      -2.060
3                    c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43      -7.870
4                                               c1ccsc1      -1.330
...                                                 ...         ...
1123                                   FC(F)(F)C(Cl)Br       -1.710
1124                          CNC(=O)ON=C(SC)C(=O)N(C)C       0.106
1125                                  CCSCCSP(=S)(OC)OC      -3.091
1126                                            CCC(C)C      -3.180
1127              COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl      -4.522

[1128 rows x 2 columns]

- Define a fuction that takes a list of smiles then it calculates some descriptor that then used to build a ML model to estimates the solubility

In [ ]:

def generate_descriptors(smiles, verbose=False):

    moldata= []
    for elem in smiles:
        mol=Chem.MolFromSmiles(elem) 
        moldata.append(mol)

    database = []
    i = 0
    for mol in moldata:        
        desc_MolWt = Descriptors.MolWt(mol)
        desc_MolLogP = Descriptors.MolLogP(mol)
        desc_MolMR = Descriptors.MolMR(mol)
        desc_HeavyAtomCount = Descriptors.HeavyAtomCount(mol)
        desc_NumHAcceptors = Descriptors.NumHAcceptors(mol)
        desc_NumHDonors = Descriptors.NumHDonors(mol)
        desc_NumHeteroatoms = Descriptors.NumHeteroatoms(mol)
        desc_NumRotatableBonds = Descriptors.NumRotatableBonds(mol)
        desc_NumValenceElectrons = Descriptors.NumValenceElectrons(mol)              
        desc_NumAromaticRings = Descriptors.NumAromaticRings(mol)        
        desc_NumSaturatedRings = Descriptors.NumSaturatedRings(mol)        
        desc_NumAliphaticRings = Descriptors.NumAliphaticRings(mol)
        desc_RingCount = Descriptors.RingCount(mol)        
        desc_TPSA = Descriptors.TPSA(mol)
        desc_LabuteASA = Descriptors.LabuteASA(mol)        
        desc_BalabanJ = Descriptors.BalabanJ(mol)
        desc_BertzCT = Descriptors.BertzCT(mol) 
                
        row = [desc_MolWt,desc_MolLogP,desc_MolMR,desc_HeavyAtomCount,desc_NumHAcceptors,desc_NumHDonors,desc_NumHeteroatoms,
                        desc_NumRotatableBonds,desc_NumValenceElectrons,desc_NumAromaticRings,desc_NumSaturatedRings,
                        desc_NumAliphaticRings,desc_RingCount,desc_TPSA,desc_LabuteASA,desc_BalabanJ,desc_BertzCT]
        if i == 0:
          database = row
          i+=1
        else:
          database = np.vstack([database, row])

    columnNames=["MolWt","MolLogP","MolMR","HeavyAtomCount","NumHAcceptors","NumHDonors","NumHeteroatoms",
                 "NumRotatableBonds","NumValenceElectrons","NumAromaticRings","NumSaturatedRings",
                 "NumAliphaticRings","RingCount","TPSA","LabuteASA","BalabanJ","BertzCT"]   

    if len (moldata) == 1:
      descriptors = pd.DataFrame([database], columns=columnNames)
    else:
      descriptors = pd.DataFrame(database, columns=columnNames)

    return descriptors

In [ ]:
# pass the smiles column as a list to this fuction to compute the descriptor

delaney_descriptor = generate_descriptors(delaney['SMILES'].tolist())

In [ ]:
delaney_descriptor

,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,457.432,-3.10802,102.2816,32.0,12.0,7.0,12.0,7.0,178.0,1.0,2.0,2.0,3.0,202.32,182.935327,1.654937,759.662938
1,201.225,2.84032,57.8402,15.0,2.0,1.0,3.0,2.0,76.0,2.0,0.0,0.0,2.0,42.24,87.724095,2.148162,459.484175
2,152.237,2.87800,48.4860,11.0,1.0,0.0,1.0,4.0,62.0,0.0,0.0,0.0,0.0,17.07,68.806046,3.625760,171.311799
3,278.354,6.29940,96.4660,22.0,0.0,0.0,0.0,0.0,102.0,5.0,0.0,0.0,5.0,0.00,128.158061,2.041379,1071.547817
4,84.143,1.74810,24.3190,5.0,1.0,0.0,1.0,0.0,26.0,1.0,0.0,0.0,1.0,0.00,35.071766,3.125000,60.124818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123,197.381,2.50850,24.6230,7.0,0.0,0.0,5.0,0.0,44.0,0.0,0.0,0.0,0.0,0.00,51.771613,3.541197,58.445472
1124,219.266,0.10710,55.1847,14.0,5.0,1.0,7.0,1.0,80.0,0.0,0.0,0.0,0.0,71.00,86.647660,4.399366,252.564575
1125,246.359,2.99000,63.7600,12.0,5.0,0.0,6.0,7.0,74.0,0.0,0.0,0.0,0.0,18.46,88.079115,3.522395,145.728624
1126,72.151,2.05240,25.1290,5.0,0.0,0.0,0.0,1.0,32.0,0.0,0.0,0.0,0.0,0.00,34.199019,2.539539,14.000000
1127,365.964,5.60150,78.0115,19.0,4.0,0.0,9.0,5.0,106.0,1.0,0.0,0.0,1.0,44.76,130.304880,3.195069,538.576344

In [ ]:
# concatenate delaney df with delaney_descriptor df into on df

delaney_cured = pd.concat([delaney, delaney_descriptor], axis=1)

In [ ]:
delaney_cured

,SMILES,Solubility,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,OCC3OC(OCC2OC(OC(C#N)c1ccccc1)C(O)C(O)C2O)C(O)...,-0.770,457.432,-3.10802,102.2816,32.0,12.0,7.0,12.0,7.0,178.0,1.0,2.0,2.0,3.0,202.32,182.935327,1.654937,759.662938
1,Cc1occc1C(=O)Nc2ccccc2,-3.300,201.225,2.84032,57.8402,15.0,2.0,1.0,3.0,2.0,76.0,2.0,0.0,0.0,2.0,42.24,87.724095,2.148162,459.484175
2,CC(C)=CCCC(C)=CC(=O),-2.060,152.237,2.87800,48.4860,11.0,1.0,0.0,1.0,4.0,62.0,0.0,0.0,0.0,0.0,17.07,68.806046,3.625760,171.311799
3,c1ccc2c(c1)ccc3c2ccc4c5ccccc5ccc43,-7.870,278.354,6.29940,96.4660,22.0,0.0,0.0,0.0,0.0,102.0,5.0,0.0,0.0,5.0,0.00,128.158061,2.041379,1071.547817
4,c1ccsc1,-1.330,84.143,1.74810,24.3190,5.0,1.0,0.0,1.0,0.0,26.0,1.0,0.0,0.0,1.0,0.00,35.071766,3.125000,60.124818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1123,FC(F)(F)C(Cl)Br,-1.710,197.381,2.50850,24.6230,7.0,0.0,0.0,5.0,0.0,44.0,0.0,0.0,0.0,0.0,0.00,51.771613,3.541197,58.445472
1124,CNC(=O)ON=C(SC)C(=O)N(C)C,0.106,219.266,0.10710,55.1847,14.0,5.0,1.0,7.0,1.0,80.0,0.0,0.0,0.0,0.0,71.00,86.647660,4.399366,252.564575
1125,CCSCCSP(=S)(OC)OC,-3.091,246.359,2.99000,63.7600,12.0,5.0,0.0,6.0,7.0,74.0,0.0,0.0,0.0,0.0,18.46,88.079115,3.522395,145.728624
1126,CCC(C)C,-3.180,72.151,2.05240,25.1290,5.0,0.0,0.0,0.0,1.0,32.0,0.0,0.0,0.0,0.0,0.00,34.199019,2.539539,14.000000
1127,COP(=O)(OC)OC(=CCl)c1cc(Cl)c(Cl)cc1Cl,-4.522,365.964,5.60150,78.0115,19.0,4.0,0.0,9.0,5.0,106.0,1.0,0.0,0.0,1.0,44.76,130.304880,3.195069,538.576344

In [ ]:
# save cured df

delaney_cured.to_csv('/content/drive/MyDrive/WithNicolas/SoulPred/delaney_cured.csv')

## T. J. Hou, K. Xia, W. Zhang, and X. J. Xu 2004 dataset

In [ ]:
# import this dataset. Source https://pubmed.ncbi.nlm.nih.gov/14741036/ and http://modem.ucsd.edu/adme/databases/databases_logS.htm

Hou_etal_dataset = pd.read_csv('/content/drive/MyDrive/WithNicolas/SoulPred/CAS_Data.csv')

In [ ]:
# This dataset is provided as CAS numbers and exp solubility

Hou_etal_dataset

       No.  CAS number  Exp. logS  Cal. logS  Residue
0        1     60-35-5       1.58       0.51     1.07
1        2     60-34-4       1.34       0.80     0.54
2        3     64-19-7       1.22       0.79     0.43
3        4    123-75-1       1.15       0.53     0.62
4        5  0127-07-01       1.12       0.69     0.43
...    ...         ...        ...        ...      ...
1285  1286  38411-22-2      -8.65      -8.46    -0.19
1286  1287     53-70-3      -8.66      -9.05     0.39
1287  1288    191-24-2      -9.03      -9.92     0.89
1288  1289  40186-72-9     -10.26     -10.56     0.30
1289  1290  52663-77-1     -10.41     -10.56     0.15

[1290 rows x 5 columns]

- Define a fuction that change CAS to SMILES using https://cactus.nci.nih.gov/chemical/structure website

In [ ]:
from urllib.request import urlopen

def CAS_to_SMILES(CAS_IDs):
    smiles_list = []
    for cas in CAS_IDs:
      try:
          url = f'http://cactus.nci.nih.gov/chemical/structure/{cas}/smiles'
          smile = urlopen(url).read().decode('utf8')
          smiles_list.append(smile)
      except:
          smiles_list.append(None)
    return smiles_list

In [ ]:
# test the fuction

CAS_to_SMILES(['40186-72-9'])

['Clc1cc(c(Cl)c(Cl)c1Cl)c2c(Cl)c(Cl)c(Cl)c(Cl)c2Cl']

In [ ]:
# now pass the col contains the cas numbers to this fuction as list to convert it to smiles and save it to pd series
# it takes app 35-40 mins to finish

Hou_etal_dataset_smiles = pd.Series(CAS_to_SMILES(Hou_etal_dataset['CAS number'].tolist()))

In [ ]:
# concatenate CAS number column, the new smile column, and solubility column togthers

Hou_etal_dataset = (
    pd.concat([Hou_etal_dataset['CAS number'], Hou_etal_dataset_smiles, Hou_etal_dataset['Exp. logS']], axis=1) 
    .rename(columns={0:'SMILES', 'Exp. logS':'Solubility'})
    .dropna()
    .reset_index(drop=True)
    
)

In [ ]:
Hou_etal_dataset

In [ ]:
# now enerate descriptors from this new smile column

Hou_etal_dataset_descriptors = generate_descriptors(Hou_etal_dataset['SMILES'].tolist())

In [ ]:
Hou_etal_dataset_descriptors

In [ ]:
# now concat the dataset df with the descriptos df

Hou_etal_dataset_cured = (
    pd.concat([Hou_etal_dataset, Hou_etal_dataset_descriptors], axis=1)
)

In [ ]:
# save the cured df 

Hou_etal_dataset_cured.to_csv('/content/drive/MyDrive/WithNicolas/SoulPred/Hou_etal_dataset_cured.csv')

## Junmei Wang, George Krudy, Tingjun Hou, Wei Zhang, George Holland, and Xiaojie Xu 2007 dataset

In [ ]:
# import this dataset. Source https://pubs.acs.org/doi/full/10.1021/ci700096r?casa_token=JQmRIoLinscAAAAA%3AMc43u7KVHSyUOa_fW6BfMvKWnoQ3HnPFpgvKqkb4E1daBmN83DPibzG67zAEDf1-GkG9GExjCEYkbvE-

Wang_etal_dataset = pd.read_csv('/content/drive/MyDrive/WithNicolas/SoulPred/Wang_dataset.csv')

In [ ]:
# extract necessary cols and rename them  

Wang_etal_dataset = (
    Wang_etal_dataset[['Smiles', 'Expt.']]
    .rename(columns={'Smiles':'SMILES', 'Expt.':'Solubility'})
)

In [ ]:
Wang_etal_dataset

                                                 SMILES  Solubility
0            BrC[2]:C[3]:C(:CH:CH:CH:@2):CH:CH:CH:CH:@3       -4.35
1                    BrC[2]:C(:C(:CH:C(:CH:@2)C#N)Br)OH       -3.33
2                     BrC[2]:C(:CH:C(:C(:CH:@2)Br)Br)Br       -6.98
3       BrC[2]:C(:CH:C(:C(:CH:@2)Cl)OP(=S)(OCH3)OCH3)Cl       -6.09
4         BrC[2]:C(:CH:C(:CH:CH:@2)NHC(=O)N(OCH3)CH3)Cl       -3.92
...                                                 ...         ...
1703  S(P(=S)(OCH3)OCH3)CH(CH2C(=O)OCH2CH3)C(=O)OCH2CH3       -3.37
1704                                   S(SCH2CH3)CH2CH3       -2.42
1705                                         S(SCH3)CH3       -1.44
1706       S(SC(=S)N(CH2CH3)CH2CH3)C(=S)N(CH2CH3)CH2CH3       -4.86
1707                   S(SC(=S)N(CH3)CH3)C(=S)N(CH3)CH3       -3.90

[1708 rows x 2 columns]

In [ ]:
# pass the smiles col to the function to generate descriptors
# this code will give an error cause for some reason the smiles are invalid and cannot convert to rdkit element

generate_descriptors(Wang_etal_dataset['SMILES'].tolist())

ArgumentError: ignored

In [ ]:
# to make sure we will print every redkit element produced from the smiles. u can see a lot on None vaalues

for smile in Wang_etal_dataset['SMILES'].tolist():
  print(Chem.MolFromSmiles(smile))

- I found an sdf file for this dataset on http://modem.ucsd.edu/adme/databases/databases_logS.htm so i use it to generate rdkit elements then valid smiles

In [ ]:
# convert sdf to smiles

with Chem.SDMolSupplier('/content/drive/MyDrive/WithNicolas/SoulPred/Wang_dataset.sdf') as supplier:
  Wang_etal_dataset_smiles_list = []
  for mol in supplier:
    if mol is not None:
      Wang_etal_dataset_smiles_list.append(Chem.MolToSmiles(mol))

In [ ]:
# print len list to make sure that 1708 smiles are produced

len(Wang_etal_dataset_smiles_list)

1708

In [ ]:
# concatnate solubility column from the csv file with smiles produced from sdf file in one df

Wang_etal_dataset = (
    pd.concat([pd.Series(Wang_etal_dataset_smiles_list, name='SMILES'), Wang_etal_dataset['Solubility']], axis=1)
)

In [ ]:
Wang_etal_dataset

                                    SMILES  Solubility
0                         Brc1cccc2ccccc12       -4.35
1                   N#Cc1cc(Br)c(O)c(Br)c1       -3.33
2                     Brc1cc(Br)c(Br)cc1Br       -6.98
3           COP(=S)(OC)Oc1cc(Cl)c(Br)cc1Cl       -6.09
4             CON(C)C(=O)Nc1ccc(Br)c(Cl)c1       -3.92
...                                    ...         ...
1703  CCOC(=O)C[C@H](SP(=S)(OC)OC)C(=O)OCC       -3.37
1704                                CCSSCC       -2.42
1705                                  CSSC       -1.44
1706            CCN(CC)C(=S)SSC(=S)N(CC)CC       -4.86
1707                CN(C)C(=S)SSC(=S)N(C)C       -3.90

[1708 rows x 2 columns]

In [ ]:
# now we can generate descriptors from ths valid smiles

Wang_etal_dataset_descriptors = generate_descriptors(Wang_etal_dataset['SMILES'].tolist())

In [ ]:
Wang_etal_dataset_descriptors

,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,207.070,3.60230,51.6480,11.0,0.0,0.0,1.0,0.0,54.0,2.0,0.0,0.0,2.0,0.00,73.980615,2.913161,374.034490
1,276.915,2.78888,48.2218,11.0,2.0,1.0,4.0,0.0,56.0,1.0,0.0,0.0,1.0,44.02,80.718254,3.348370,306.697838
2,393.698,4.73660,57.2420,10.0,0.0,0.0,4.0,0.0,54.0,1.0,0.0,0.0,1.0,0.00,92.901594,3.282463,205.919883
3,366.000,4.65200,73.0930,16.0,4.0,0.0,8.0,4.0,90.0,1.0,0.0,0.0,1.0,27.69,117.355931,3.063767,435.536754
4,293.548,3.12760,62.9427,15.0,2.0,1.0,6.0,2.0,82.0,1.0,0.0,0.0,1.0,41.57,101.235845,2.729689,373.130019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,330.364,2.12180,77.5650,19.0,8.0,0.0,9.0,9.0,112.0,0.0,0.0,0.0,0.0,71.06,121.965908,4.807811,340.911579
1704,122.258,2.40760,36.2640,6.0,2.0,0.0,2.0,3.0,38.0,0.0,0.0,0.0,0.0,0.00,47.480260,2.339092,17.509775
1705,94.204,1.62740,27.0300,4.0,2.0,0.0,2.0,1.0,26.0,0.0,0.0,0.0,0.0,0.00,34.750375,1.974745,6.000000
1706,296.552,3.62120,86.2200,16.0,4.0,0.0,6.0,4.0,94.0,0.0,0.0,0.0,0.0,6.48,117.907140,4.041784,200.858919
1707,240.444,2.06080,67.7520,12.0,4.0,0.0,6.0,0.0,70.0,0.0,0.0,0.0,0.0,6.48,92.447372,3.693483,158.386899

In [ ]:
# concatenate Wang_etal_dataset_descriptors with Wang_etal_dataset

Wang_etal_dataset_cured = pd.concat([Wang_etal_dataset, Wang_etal_dataset_descriptors], axis=1)

In [ ]:
Wang_etal_dataset_cured

,SMILES,Solubility,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,Brc1cccc2ccccc12,-4.35,207.070,3.60230,51.6480,11.0,0.0,0.0,1.0,0.0,54.0,2.0,0.0,0.0,2.0,0.00,73.980615,2.913161,374.034490
1,N#Cc1cc(Br)c(O)c(Br)c1,-3.33,276.915,2.78888,48.2218,11.0,2.0,1.0,4.0,0.0,56.0,1.0,0.0,0.0,1.0,44.02,80.718254,3.348370,306.697838
2,Brc1cc(Br)c(Br)cc1Br,-6.98,393.698,4.73660,57.2420,10.0,0.0,0.0,4.0,0.0,54.0,1.0,0.0,0.0,1.0,0.00,92.901594,3.282463,205.919883
3,COP(=S)(OC)Oc1cc(Cl)c(Br)cc1Cl,-6.09,366.000,4.65200,73.0930,16.0,4.0,0.0,8.0,4.0,90.0,1.0,0.0,0.0,1.0,27.69,117.355931,3.063767,435.536754
4,CON(C)C(=O)Nc1ccc(Br)c(Cl)c1,-3.92,293.548,3.12760,62.9427,15.0,2.0,1.0,6.0,2.0,82.0,1.0,0.0,0.0,1.0,41.57,101.235845,2.729689,373.130019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1703,CCOC(=O)C[C@H](SP(=S)(OC)OC)C(=O)OCC,-3.37,330.364,2.12180,77.5650,19.0,8.0,0.0,9.0,9.0,112.0,0.0,0.0,0.0,0.0,71.06,121.965908,4.807811,340.911579
1704,CCSSCC,-2.42,122.258,2.40760,36.2640,6.0,2.0,0.0,2.0,3.0,38.0,0.0,0.0,0.0,0.0,0.00,47.480260,2.339092,17.509775
1705,CSSC,-1.44,94.204,1.62740,27.0300,4.0,2.0,0.0,2.0,1.0,26.0,0.0,0.0,0.0,0.0,0.00,34.750375,1.974745,6.000000
1706,CCN(CC)C(=S)SSC(=S)N(CC)CC,-4.86,296.552,3.62120,86.2200,16.0,4.0,0.0,6.0,4.0,94.0,0.0,0.0,0.0,0.0,6.48,117.907140,4.041784,200.858919
1707,CN(C)C(=S)SSC(=S)N(C)C,-3.90,240.444,2.06080,67.7520,12.0,4.0,0.0,6.0,0.0,70.0,0.0,0.0,0.0,0.0,6.48,92.447372,3.693483,158.386899

In [ ]:
# save cured df

Wang_etal_dataset_cured.to_csv('/content/drive/MyDrive/WithNicolas/SoulPred/Wang_dataset_cured.csv', index=False)

#Combining all datasets in one bid dataset

In [ ]:
# chech that all of them have the same shape

print(AqSolDB_cured.shape)
print(Wang_etal_dataset_cured.shape)
print(delaney_cured.shape)
print(Hou_etal_dataset_cured.shape)

(9982, 19)
(1708, 19)
(1128, 19)
(1116, 21)

In [ ]:
# Hou_etal_dataset_cured has two extra cols 

Hou_etal_dataset_cured.columns

Index(['Unnamed: 0', 'CAS number', 'SMILES', 'Solubility', 'MolWt', 'MolLogP',
       'MolMR', 'HeavyAtomCount', 'NumHAcceptors', 'NumHDonors',
       'NumHeteroatoms', 'NumRotatableBonds', 'NumValenceElectrons',
       'NumAromaticRings', 'NumSaturatedRings', 'NumAliphaticRings',
       'RingCount', 'TPSA', 'LabuteASA', 'BalabanJ', 'BertzCT'],
      dtype='object')

In [ ]:
mega_dataset = (
    pd.concat([AqSolDB_cured, Wang_etal_dataset_cured, delaney_cured, Hou_etal_dataset_cured.drop(columns=['CAS number', 'Unnamed: 0'])]) # adding all 4 datasets together
    .drop_duplicates(subset='SMILES') # remove any duplicated compound between datasets
)

In [ ]:
# the mega_dataset contain all data from 4 datasets after removing dubpicates. 13934 ---> 11714

mega_dataset

,SMILES,Solubility,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,392.510,3.9581,102.4454,23.0,0.0,0.0,2.0,17.0,142.0,0.0,0.0,0.0,0.0,0.00,158.520601,0.000000e+00,210.377334
1,O=C1Nc2cccc3cccc1c23,-3.254767,169.183,2.4055,51.9012,13.0,1.0,1.0,2.0,0.0,62.0,2.0,0.0,1.0,3.0,29.10,75.183563,2.582996e+00,511.229248
2,Clc1ccc(C=O)cc1,-2.177078,140.569,2.1525,36.8395,9.0,1.0,0.0,2.0,1.0,46.0,1.0,0.0,0.0,1.0,17.07,58.261134,3.009782e+00,202.661065
3,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,756.226,8.1161,200.7106,53.0,6.0,2.0,7.0,10.0,264.0,6.0,0.0,0.0,6.0,120.72,323.755434,2.322963e-07,1964.648666
4,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,422.525,2.4854,119.0760,31.0,6.0,0.0,6.0,12.0,164.0,2.0,4.0,4.0,6.0,56.60,183.183268,1.084427e+00,769.899934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,Clc1ccc(Cl)c(c1)c2cc(Cl)ccc2Cl,-7.000000,291.992,5.9672,71.9180,16.0,0.0,0.0,4.0,1.0,82.0,2.0,0.0,0.0,2.0,0.00,113.701562,2.661683e+00,485.037124
1101,Clc1cc(c2ccccc2)c(Cl)c(Cl)c1Cl,-7.160000,291.992,5.9672,71.9180,16.0,0.0,0.0,4.0,1.0,82.0,2.0,0.0,0.0,2.0,0.00,113.701562,2.677072e+00,520.287124
1104,c1ccc2c(c1)c3cccc4ccc5cccc2c5c34,-7.800000,252.316,5.7372,87.6520,20.0,0.0,0.0,0.0,0.0,92.0,5.0,0.0,0.0,5.0,0.00,116.137086,2.329151e+00,998.004970
1105,Clc1ccc(Cl)c(c1)c2ccc(Cl)c(Cl)c2Cl,-7.910000,326.437,6.6206,76.9280,17.0,0.0,0.0,5.0,1.0,88.0,2.0,0.0,0.0,2.0,0.00,124.004828,2.687036e+00,577.348938
1114,Clc1cc(c(Cl)c(Cl)c1Cl)c2c(Cl)c(Cl)c(Cl)c(Cl)c2Cl,-10.260000,464.217,9.2342,96.9680,21.0,0.0,0.0,9.0,1.0,112.0,2.0,0.0,0.0,2.0,0.00,165.217893,2.928344e+00,722.364038

- one problem with SMILES that some compounds can have many valied SMILES, so it good to change SMILES to canonical smiles then droup duplicates

In [ ]:
# create new col with canonical smiles

mega_dataset['SMILES_FROM_RDKIT'] = mega_dataset['SMILES'].apply(lambda x: Chem.MolToSmiles(Chem.MolFromSmiles(x)))

In [ ]:
mega_dataset

,SMILES,Solubility,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT,SMILES_FROM_RDKIT
0,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,392.510,3.9581,102.4454,23.0,0.0,0.0,2.0,17.0,142.0,0.0,0.0,0.0,0.0,0.00,158.520601,0.000000e+00,210.377334,CCCCCCCCCCCCCCCCCC[N+](C)(C)C.[Br-]
1,O=C1Nc2cccc3cccc1c23,-3.254767,169.183,2.4055,51.9012,13.0,1.0,1.0,2.0,0.0,62.0,2.0,0.0,1.0,3.0,29.10,75.183563,2.582996e+00,511.229248,O=C1Nc2cccc3cccc1c23
2,Clc1ccc(C=O)cc1,-2.177078,140.569,2.1525,36.8395,9.0,1.0,0.0,2.0,1.0,46.0,1.0,0.0,0.0,1.0,17.07,58.261134,3.009782e+00,202.661065,O=Cc1ccc(Cl)cc1
3,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,756.226,8.1161,200.7106,53.0,6.0,2.0,7.0,10.0,264.0,6.0,0.0,0.0,6.0,120.72,323.755434,2.322963e-07,1964.648666,CC(c1ccccc1)c1cc(C(=O)[O-])c(O)c(C(C)c2ccccc2)...
4,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,422.525,2.4854,119.0760,31.0,6.0,0.0,6.0,12.0,164.0,2.0,4.0,4.0,6.0,56.60,183.183268,1.084427e+00,769.899934,c1cc(N(CC2CO2)CC2CO2)ccc1Cc1ccc(N(CC2CO2)CC2CO...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,Clc1ccc(Cl)c(c1)c2cc(Cl)ccc2Cl,-7.000000,291.992,5.9672,71.9180,16.0,0.0,0.0,4.0,1.0,82.0,2.0,0.0,0.0,2.0,0.00,113.701562,2.661683e+00,485.037124,Clc1ccc(Cl)c(-c2cc(Cl)ccc2Cl)c1
1101,Clc1cc(c2ccccc2)c(Cl)c(Cl)c1Cl,-7.160000,291.992,5.9672,71.9180,16.0,0.0,0.0,4.0,1.0,82.0,2.0,0.0,0.0,2.0,0.00,113.701562,2.677072e+00,520.287124,Clc1cc(-c2ccccc2)c(Cl)c(Cl)c1Cl
1104,c1ccc2c(c1)c3cccc4ccc5cccc2c5c34,-7.800000,252.316,5.7372,87.6520,20.0,0.0,0.0,0.0,0.0,92.0,5.0,0.0,0.0,5.0,0.00,116.137086,2.329151e+00,998.004970,c1ccc2c(c1)c1cccc3ccc4cccc2c4c31
1105,Clc1ccc(Cl)c(c1)c2ccc(Cl)c(Cl)c2Cl,-7.910000,326.437,6.6206,76.9280,17.0,0.0,0.0,5.0,1.0,88.0,2.0,0.0,0.0,2.0,0.00,124.004828,2.687036e+00,577.348938,Clc1ccc(Cl)c(-c2ccc(Cl)c(Cl)c2Cl)c1
1114,Clc1cc(c(Cl)c(Cl)c1Cl)c2c(Cl)c(Cl)c(Cl)c(Cl)c2Cl,-10.260000,464.217,9.2342,96.9680,21.0,0.0,0.0,9.0,1.0,112.0,2.0,0.0,0.0,2.0,0.00,165.217893,2.928344e+00,722.364038,Clc1cc(-c2c(Cl)c(Cl)c(Cl)c(Cl)c2Cl)c(Cl)c(Cl)c1Cl

In [ ]:
mega_dataset_cured = (
    mega_dataset.drop_duplicates(subset=['SMILES_FROM_RDKIT'], ignore_index=True)
    .drop(columns=['SMILES_FROM_RDKIT'])
)

In [ ]:
# As expected some compounds has been removed. 11714 ----> 10379

mega_dataset_cured

,SMILES,Solubility,MolWt,MolLogP,MolMR,HeavyAtomCount,NumHAcceptors,NumHDonors,NumHeteroatoms,NumRotatableBonds,NumValenceElectrons,NumAromaticRings,NumSaturatedRings,NumAliphaticRings,RingCount,TPSA,LabuteASA,BalabanJ,BertzCT
0,[Br-].CCCCCCCCCCCCCCCCCC[N+](C)(C)C,-3.616127,392.510,3.9581,102.4454,23.0,0.0,0.0,2.0,17.0,142.0,0.0,0.0,0.0,0.0,0.00,158.520601,0.000000e+00,210.377334
1,O=C1Nc2cccc3cccc1c23,-3.254767,169.183,2.4055,51.9012,13.0,1.0,1.0,2.0,0.0,62.0,2.0,0.0,1.0,3.0,29.10,75.183563,2.582996e+00,511.229248
2,Clc1ccc(C=O)cc1,-2.177078,140.569,2.1525,36.8395,9.0,1.0,0.0,2.0,1.0,46.0,1.0,0.0,0.0,1.0,17.07,58.261134,3.009782e+00,202.661065
3,[Zn++].CC(c1ccccc1)c2cc(C(C)c3ccccc3)c(O)c(c2)...,-3.924409,756.226,8.1161,200.7106,53.0,6.0,2.0,7.0,10.0,264.0,6.0,0.0,0.0,6.0,120.72,323.755434,2.322963e-07,1964.648666
4,C1OC1CN(CC2CO2)c3ccc(Cc4ccc(cc4)N(CC5CO5)CC6CO...,-4.662065,422.525,2.4854,119.0760,31.0,6.0,0.0,6.0,12.0,164.0,2.0,4.0,4.0,6.0,56.60,183.183268,1.084427e+00,769.899934
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10374,CN(C)[C@H]1[C@@H]2C[C@H]3C(=C(O)c4c(O)cccc4[C@...,-1.420000,590.586,-0.0345,143.5146,42.0,13.0,7.0,15.0,4.0,228.0,1.0,3.0,4.0,5.0,234.24,239.625001,9.521048e-07,1392.080754
10375,CCC(N)Cc1c[nH]c2ccccc12.CC(O)=O,-2.570000,248.326,2.5386,73.5789,18.0,2.0,3.0,4.0,3.0,98.0,2.0,0.0,0.0,2.0,79.11,106.813358,3.567857e-07,501.218230
10376,[Na+].[O-]C(=O)Cc1c(Cl)ccc(Cl)c1Cl,-3.080000,261.467,-1.0568,50.1830,14.0,2.0,0.0,6.0,2.0,70.0,1.0,0.0,0.0,1.0,40.13,118.440242,1.690000e-06,354.684783
10377,O.O.O.O.O.CN1CC[C@]23[C@H]4Oc5c(O)ccc(C[C@@H]1...,-3.280000,473.497,-3.5782,109.8230,31.0,6.0,4.0,14.0,0.0,182.0,1.0,1.0,4.0,5.0,285.03,178.236157,0.000000e+00,883.343327
10378,C[C@]12CCC(=O)C=C1CC[C@H]3[C@@H]4CC[C@H](C(=O)...,-3.850000,360.450,1.8457,94.0726,26.0,5.0,2.0,5.0,3.0,142.0,0.0,3.0,4.0,4.0,91.67,153.398199,1.735726e+00,681.888922

In [ ]:
# save mega_dataset_cured to be used to train the ML model

mega_dataset_cured.to_csv('/content/drive/MyDrive/WithNicolas/SoulPred/mega_dataset_cured.csv', index=False)